Issue 1 create an entry -Euichang Park
EuichangPark/code-journal pull request #5
Opened 2022-02-15 20:46 UTC by EuichangPark

![Capture](https://user-images.githubusercontent.com/96793078/154146355-9e8eb5cb-459a-45b0-aa02-8e40caa655ea.PNG)

2022-02-15 23:13 UTC, EuichangPark commented
![377width](https://user-images.githubusercontent.com/96793078/154165682-88863cd9-e368-4d30-933d-fdcc86452c0d.PNG)
![780width](https://user-images.githubusercontent.com/96793078/154165684-199ae79d-df2a-4b77-90d9-9299f758af94.PNG)
![daty entry](https://user-images.githubusercontent.com/96793078/154165685-ab6d148b-8607-4e5d-ab7f-67d73e8c8a37.PNG)
![entryId increases](https://user-images.githubusercontent.com/96793078/154165686-65500a92-3e75-432d-85a4-2ebaeb4443cf.PNG)
![photo preview](https://user-images.githubusercontent.com/96793078/154165688-c855c9c9-401e-4fc3-bffb-b64ad6ad13a8.PNG)

2022-02-15 23:17 UTC, Zhiwutian requested changes
small functionality update needed

2022-02-15 23:17 UTC, Zhiwutian commented on js/main.js
> +  myObject.entryId = data.nextEntryId + 1;
here you should just use `data.nextEntryId` then increment it on the next line as you are doing

2022-02-16 00:41 UTC, EuichangPark commented
![377width](https://user-images.githubusercontent.com/96793078/154174141-45c94483-db9a-4332-ac88-d3cf8e1dca0c.PNG)
![780width](https://user-images.githubusercontent.com/96793078/154174143-468cdc72-ec8f-43e3-a544-e39f0ab85fd1.PNG)
![entryId increases](https://user-images.githubusercontent.com/96793078/154174144-1dc40414-7959-4c5f-a3aa-b559978909f8.PNG)
![input focus](https://user-images.githubusercontent.com/96793078/154174146-183dec2a-93ab-43a4-9990-beb131969979.PNG)
![photo preview](https://user-images.githubusercontent.com/96793078/154174147-13e49b25-b72c-47bc-826b-8e0ae2609ec4.PNG)

2022-02-16 01:17 UTC, Zhiwutian approved these changes
👍🏼

2022-02-16 01:18 UTC, merged